added human basic movement and added player death
reyhan0173/Pixel-Game-Jam pull request #9
Opened 2024-05-13 16:52 UTC by reyhan0173

- Created Human
   * Added patrol and idle states for now, still need to implement other active states
   * uses area2d for detection
 - Added player death function
   * Hitbox scene added to enemies
   * This area2d sends a signal to the player once it enters the enemy body
   * Signal calls player_die (currently commented out to help test other things)

2024-05-13 20:58 UTC, jaekit requested changes
@reyhan0173
I would at least like to keep some things consistent:
- the file naming convention. We'll just use snake_case for all file names
- generally following [GDScript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html) including:
  - correct spacing between functions
  - maintaining proper indentation within scopes
  - inline `@onready` tags
  - putting `:=` together with no space
  - Only exception is first line where `class_name` and `extends` will go on the same line

2024-05-13 20:58 UTC, jaekit commented on scenes/roombot.tscn
The roombot's collisionshape is not centered btw

2024-05-13 20:58 UTC, jaekit commented on scripts/roombot/Roombot.gd
>  var state_machine = $state_machine
Give state_machine.gd a class_name and infer the type of this variable using :=

2024-05-13 20:58 UTC, jaekit commented on scripts/human/human.gd
> +var state_machine = $state_machine
same here. infer the type after adding a class_name

2024-05-13 20:58 UTC, jaekit commented on scenes/Hitbox.gd
should delete this file if it is unused

2024-05-13 20:58 UTC, jaekit commented on scripts/state_machine.gd
It's kinda weird to create your own process_physics/process_frame functions instead of using the built-ins. I see you've created them to return a value, but really the states should emit a signal to the state machine to request a change in the state, rather than returning it via a function. No need to change it now though.

2024-05-13 20:58 UTC, jaekit commented on scripts/state_machine.gd
Mind you, if you use the built-ins, they will always run which is why you enable/disable processing when you switch in and out of states.

2024-05-13 20:58 UTC, jaekit commented on scripts/enemy_state.gd
why is this the only class with snake_cased class_name :(

2024-05-14 09:48 UTC, reyhan0173 commented on scenes/Hitbox.gd
This file is used, its just currently commented out so that the player doesn't keep dying when we're trying to test enemy movement

2024-05-14 19:59 UTC, jaekit approved these changes

2024-05-14 20:01 UTC, merged